[package]
name = "rtml"
version = "0.1.0"
authors = ["Azi Crawford <azicrawford@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rtml"
